#ifndef INC_DRIVER_HALL_EFFECT_H_
#define INC_DRIVER_HALL_EFFECT_H_

#include <inttypes.h>
#include "stm32u575xx.h"

extern uint32_t hall_effect_cols;
extern uint16_t hall_effect_rows;

#define ROW0_IDR	GPIO_IDR_ID6	// GPIOA
#define ROW1_IDR	GPIO_IDR_ID7	// GPIOA
#define ROW2_IDR	GPIO_IDR_ID4	// GPIOC
#define ROW3_IDR	GPIO_IDR_ID5	// GPIOC
#define ROW4_IDR	GPIO_IDR_ID1	// GPIOB
#define ROW5_IDR	GPIO_IDR_ID2	// GPIOB
#define ROW6_IDR	GPIO_IDR_ID7	// GPIOE
#define ROW7_IDR	GPIO_IDR_ID8	// GPIOE
#define ROW8_IDR	GPIO_IDR_ID9	// GPIOE
#define ROW9_IDR	GPIO_IDR_ID10	// GPIOE
#define ROW10_IDR	GPIO_IDR_ID11	// GPIOE
#define ROW11_IDR	GPIO_IDR_ID12	// GPIOE
#define ROW12_IDR	GPIO_IDR_ID13	// GPIOE
#define ROW13_IDR	GPIO_IDR_ID14	// GPIOE
#define ROW14_IDR	GPIO_IDR_ID15	// GPIOE
#define ROW15_IDR	GPIO_IDR_ID10	// GPIOB

#define COL0_IDR	GPIO_IDR_ID2	// GPIOE
#define COL1_IDR	GPIO_IDR_ID1	// GPIOE
#define COL2_IDR	GPIO_IDR_ID0	// GPIOE
#define COL3_IDR	GPIO_IDR_ID9	// GPIOB
#define COL4_IDR	GPIO_IDR_ID8	// GPIOB
#define COL5_IDR	GPIO_IDR_ID7	// GPIOB
#define COL6_IDR	GPIO_IDR_ID6	// GPIOB
#define COL7_IDR	GPIO_IDR_ID5	// GPIOB
#define COL8_IDR	GPIO_IDR_ID4	// GPIOB
#define COL9_IDR	GPIO_IDR_ID3	// GPIOB
#define COL10_IDR	GPIO_IDR_ID7	// GPIID
#define COL11_IDR	GPIO_IDR_ID6	// GPIID
#define COL12_IDR	GPIO_IDR_ID5	// GPIID
#define COL13_IDR	GPIO_IDR_ID4	// GPIID
#define COL14_IDR	GPIO_IDR_ID3	// GPIID
#define COL15_IDR	GPIO_IDR_ID2	// GPIID
#define COL16_IDR	GPIO_IDR_ID1	// GPIID
#define COL17_IDR	GPIO_IDR_ID0	// GPIID
#define COL18_IDR	GPIO_IDR_ID12	// GPIOC
#define COL19_IDR	GPIO_IDR_ID11	// GPIOC
#define COL20_IDR	GPIO_IDR_ID10	// GPIOC
#define COL21_IDR	GPIO_IDR_ID15	// GPIOA
#define COL22_IDR	GPIO_IDR_ID12	// GPIOA
#define COL23_IDR	GPIO_IDR_ID11	// GPIOA
#define COL24_IDR	GPIO_IDR_ID10	// GPIOA
#define COL25_IDR	GPIO_IDR_ID9	// GPIOA
#define COL26_IDR	GPIO_IDR_ID8	// GPIOA
#define COL27_IDR	GPIO_IDR_ID9	// GPIOC
#define COL28_IDR	GPIO_IDR_ID8	// GPIOC
#define COL29_IDR	GPIO_IDR_ID7	// GPIOC
#define COL30_IDR	GPIO_IDR_ID6	// GPIOC
#define COL31_IDR	GPIO_IDR_ID15	// GPIID

void Driver_Hall_Effect_ReadHalls();

#endif /* INC_DRIVER_HALL_EFFECT_H_ */
