#ifndef INC_DRIVER_HALL_EFFECT_H_
#define INC_DRIVER_HALL_EFFECT_H_

#include <inttypes.h>
#include "stm32u575xx.h"

extern uint32_t hall_effect_cols;
extern uint16_t hall_effect_rows;

#define ROW0_ODR	GPIO_ODR_OD6	// GPIOA
#define ROW1_ODR	GPIO_ODR_OD7	// GPIOA
#define ROW2_ODR	GPIO_ODR_OD4	// GPIOC
#define ROW3_ODR	GPIO_ODR_OD5	// GPIOC
#define ROW4_ODR	GPIO_ODR_OD1	// GPIOB
#define ROW5_ODR	GPIO_ODR_OD2	// GPIOB
#define ROW6_ODR	GPIO_ODR_OD7	// GPIOE
#define ROW7_ODR	GPIO_ODR_OD8	// GPIOE
#define ROW8_ODR	GPIO_ODR_OD9	// GPIOE
#define ROW9_ODR	GPIO_ODR_OD10	// GPIOE
#define ROW10_ODR	GPIO_ODR_OD11	// GPIOE
#define ROW11_ODR	GPIO_ODR_OD12	// GPIOE
#define ROW12_ODR	GPIO_ODR_OD13	// GPIOE
#define ROW13_ODR	GPIO_ODR_OD14	// GPIOE
#define ROW14_ODR	GPIO_ODR_OD15	// GPIOE
#define ROW15_ODR	GPIO_ODR_OD10	// GPIOB

#define COL0_ODR	GPIO_ODR_OD2	// GPIOE
#define COL1_ODR	GPIO_ODR_OD1	// GPIOE
#define COL2_ODR	GPIO_ODR_OD0	// GPIOE
#define COL3_ODR	GPIO_ODR_OD9	// GPIOB
#define COL4_ODR	GPIO_ODR_OD8	// GPIOB
#define COL5_ODR	GPIO_ODR_OD7	// GPIOB
#define COL6_ODR	GPIO_ODR_OD6	// GPIOB
#define COL7_ODR	GPIO_ODR_OD5	// GPIOB
#define COL8_ODR	GPIO_ODR_OD4	// GPIOB
#define COL9_ODR	GPIO_ODR_OD3	// GPIOB
#define COL10_ODR	GPIO_ODR_OD7	// GPIOD
#define COL11_ODR	GPIO_ODR_OD6	// GPIOD
#define COL12_ODR	GPIO_ODR_OD5	// GPIOD
#define COL13_ODR	GPIO_ODR_OD4	// GPIOD
#define COL14_ODR	GPIO_ODR_OD3	// GPIOD
#define COL15_ODR	GPIO_ODR_OD2	// GPIOD
#define COL16_ODR	GPIO_ODR_OD1	// GPIOD
#define COL17_ODR	GPIO_ODR_OD0	// GPIOD
#define COL18_ODR	GPIO_ODR_OD12	// GPIOC
#define COL19_ODR	GPIO_ODR_OD11	// GPIOC
#define COL20_ODR	GPIO_ODR_OD10	// GPIOC
#define COL21_ODR	GPIO_ODR_OD15	// GPIOA
#define COL22_ODR	GPIO_ODR_OD12	// GPIOA
#define COL23_ODR	GPIO_ODR_OD11	// GPIOA
#define COL24_ODR	GPIO_ODR_OD10	// GPIOA
#define COL25_ODR	GPIO_ODR_OD9	// GPIOA
#define COL26_ODR	GPIO_ODR_OD8	// GPIOA
#define COL27_ODR	GPIO_ODR_OD9	// GPIOC
#define COL28_ODR	GPIO_ODR_OD8	// GPIOC
#define COL29_ODR	GPIO_ODR_OD7	// GPIOC
#define COL30_ODR	GPIO_ODR_OD6	// GPIOC
#define COL31_ODR	GPIO_ODR_OD15	// GPIOD

void Driver_Hall_Effect_ReadHalls();

#endif /* INC_DRIVER_HALL_EFFECT_H_ */
